events {}

http {
    server_tokens off;

    server {
        listen 80;
        server_name inktime-ci.acme.dev;
        return 301 https://$host:8443$request_uri;
    }

    server {
        listen 443 ssl;
        server_name inktime-ci.acme.dev;

        ssl_certificate /etc/nginx/tls/server.crt;
        ssl_certificate_key /etc/nginx/tls/server.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass http://inktime-web:8765;
            proxy_http_version 1.1;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Port 8443;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}

